
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_connect
    username: mukesh-silwal
    password: $@31Brother
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:



    hibernate:
      ddl-auto: update

  application:
    name: ORDER-USER




eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8088




